---
- name: Copy sudoers file for editing
  copy:
    remote_src: true
    src: "/etc/sudoers"
    dest: "/etc/sudoers.tmp"

- name: Ensure passwordless sudo for {{ admin_group }} group
  lineinfile:
    dest: "/etc/sudoers.tmp"
    state: present
    regexp: "^%{{ admin_group }}"
    line: "%{{ admin_group }} ALL=(ALL) NOPASSWD: ALL"
  register: sudoers_wheel_conf

- name: Final sudoers file check
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
  when: sudoers_wheel_conf.changed == true
